version: 2

models:
  - name: trs_campaigns
    columns:
      - name: campaign_id
        description: primary key
        tests:
          - not_null
          - unique
      - name: channel_id
        description: foreign key to trs_channels
        tests:
          - not_null
          - relationships:
              to: ref('trs_channels')
              field: channel_id

  - name: trs_campaign_performance
    columns:
      - name: performance_id
        description: primary key
        tests:
          - not_null
          - unique
      - name: campaign_id
        description: foreign key to trs_campaigns
        tests:
          - not_null
          - relationships:
              to: ref('trs_campaigns')
              field: campaign_id

  - name: trs_channels
    columns:
      - name: channel_id
        description: primary key
        tests:
          - not_null
          - unique

  - name: trs_email_campaigns
    columns:
      - name: email_campaign_id
        description: primary key
        tests:
          - not_null
          - unique
      - name: campaign_id
        description: foreign key to trs_campaigns
        tests:
          - not_null
          - relationships:
              to: ref('trs_campaigns')
              field: campaign_id
      - name: list_id
        description: foreign key to trs_email_lists
        tests:
          - not_null
          - relationships:
              to: ref('trs_email_lists')
              field: list_id

  - name: trs_email_lists
    columns:
      - name: list_id
        description: primary key
        tests:
          - not_null
          - unique

  - name: trs_subscribers
    columns:
      - name: subscriber_id
        description: primary key
        tests:
          - not_null
          - unique